### PR TITLE
test mkl cluster support

### PR DESCRIPTION
**Pull request by rscohn2**

### CODE REVIEW

**Comment by rscohn2** [comment]
@he-b: I am getting a failure related to static linking. Can you look at it?

```
'make' '-j2' '-C' 'samples' 'PREFIX=/home/runner/work/oneapi-spack-tests/oneapi-spack-tests/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.3.0/oneapi-test-basic-main-5q2dy4qq7cp5xpr3nqyaqc6zwxu5awzh' 'SCALAPACK_LD_FLAGS=-L/home/runner/work/oneapi-spack-tests/oneapi-spack-tests/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-10.3.0/intel-oneapi-mkl-2021.3.0-pgawho7zfp5gpdp4uo7sd4ofa3s4jb3j/mkl/2021.3.0/lib/intel64 -L/lib/x86_64-linux-gnu -l-Wl,--start-group -lmkl_scalapack_lp64 -lmkl_cdft_core -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_lp64 -l-Wl,--end-group -lpthread -lm -ldl' 'scalapack-sample.out'

3 errors found in build log:
  >> 5    /usr/bin/ld: cannot find -l-Wl,--start-group
  >> 6    /usr/bin/ld: cannot find -l-Wl,--end-group
  >> 7    collect2: error: ld returned 1 exit status
     8    make: *** [Makefile:48: scalapack-sample] Error 1
     9    make: Leaving directory '/tmp/runner/spack-stage/spack-stage-oneapi-t
          est-basic-main-5q2dy4qq7cp5xpr3nqyaqc6zwxu5awzh/spack-src/samples'
```

The value for SCALAPACK_LD_FLAGS comes from here: https://github.com/rscohn2/oneapi-spack-tests/blob/9d00f61f28e8acb32eb003e7bc4d5355c7173c45/repo/packages/oneapi-test-basic/package.py#L74

I think the problem is that you cannot add things that are not libs here: https://github.com/spack/spack/blob/40889a3b9ba77a54ccbaa747bcfa77bb9c192239/var/spack/repos/builtin/packages/intel-oneapi-mkl/package.py#L85

**Comment by scheibelp** [comment]
https://github.com/spack/spack/blob/40889a3b9ba77a54ccbaa747bcfa77bb9c192239/var/spack/repos/builtin/packages/intel-oneapi-mkl/package.py#L85 adds `Wl,--start-group` as if it were the name of a library. Currently the LibraryList object provided by Spack isn't sophisticated enough to allow you to encode this, but you can create your own object which has all the same functions like:

```
OneApiLinkerOptions(object):
  @property
  def link_flags(self):
    return ['-Wl,--start-group', '-lfoo', '-lbar',...]

  @property
  def search_flags(self)
    ...

  @property
  def link_flags(self)
    return self.search_flags + self.link_flags
```

Does that make sense?

**Comment by he-b** [comment]
@scheibelp thank you for your suggestion, do you know of any package that creates its own object in a similar way? thanks.

**Comment by scheibelp** [comment]
> do you know of any package that creates its own object in a similar way? thanks.

I do not. Although the suggestion above outlined what it should look like. Something a bit closer to the finished product:

(EDITED: I originally had two functions here called `link_flags`)

```
@property
def libs(self):
  return OneapiLinkerOptions(self.spec)

OneapiLinkerOptions(object):
  def __init__(self, spec)
    self.spec = spec

  @property
  def link_flags(self):
    return ['-Wl,--start-group', '-lfoo', '-lbar',...]

  @property
  def search_flags(self)
    return ['-L{0}'.format(self.spec.prefix.lib)]

  @property
  def ld_flags(self)
    return self.search_flags + self.link_flags
```

Let me know if more context would be useful.

**Comment by rscohn2** [comment]
It looks like there are 2 functions called link_flags. Should one of them be ld_flags?

**Comment by scheibelp** [comment]
> It looks like there are 2 functions called link_flags. Should one of them be ld_flags?

Yes - thanks! I have updated https://github.com/rscohn2/oneapi-spack-tests/pull/19#issuecomment-936765442 to fix that

**Comment by rscohn2** [comment]
@he-b: Some of the other oneapi libraries need the same thing to support static, so it is better if I put it in oneapi.py where it can be shared among packages. It might take me a couple weeks before I have time to do this.

**Pull request merged**
